name: movie
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#State Management
  get: ^4.6.6

  #API
  http: ^1.2.0

  #Key Safety
  flutter_dotenv: ^5.1.0

  #Animations
  lottie: ^3.1.0
  
  #Auth
  url_launcher: ^6.2.5
  flutter_web_auth: ^0.5.0
  webview_flutter: ^4.7.0

  #Local Database,Offline Cache
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/VarelaRound-Regular.ttf

